/** Única superficie pública de la feature (§4). */
export { MobileShell } from './components/MobileShell'
export { Phase2Page } from './pages/Phase2Page'
export { Phase3Page } from './pages/Phase3Page'
export { NotificationsPage } from './pages/NotificationsPage'
export { HomePage } from './pages/HomePage'
export { PasswordPage } from './pages/PasswordPage'
export { PermissionsPage } from './pages/PermissionsPage'
export { ProfilePage } from './pages/ProfilePage'
export { PunchPage } from './pages/PunchPage'
